In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\yhk25\.conda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [8]:
median_salary_year = df['salary_year_avg'].median()

In [9]:
median_salary_hour = df['salary_hour_avg'].median()

In [10]:
df_filled = df

In [11]:
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [12]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [13]:
df_unique = df_filled

In [14]:
df_unique = df_unique.drop_duplicates()

In [15]:
print('Length of original df: ', len(df_filled))
print('Length of drop duplicates df: ', len(df_unique))
print('Rows Dropped: ', len(df_filled) - len(df_unique))

Length of original df:  785741
Length of drop duplicates df:  785640
Rows Dropped:  101

In [16]:
df_unique = df_unique.drop_duplicates(subset = ['job_title', 'company_name'])

print('Length of original df: ', len(df_filled))
print('Length of drop duplicates df: ', len(df_unique))
print('Rows Dropped: ', len(df_filled) - len(df_unique))

Length of original df:  785741
Length of drop duplicates df:  508042
Rows Dropped:  277699

In [2]:
df_cleaned = df.dropna(how = 'all')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [3]:
df_cleaned.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [4]:
df_z_filled = df_cleaned.fillna(0)

In [6]:
df_z_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               0.0              0.0
1               0.0              0.0
2               0.0              0.0
3               0.0              0.0
4               0.0              0.0
5               0.0              0.0
6               0.0              0.0
7               0.0              0.0
8               0.0              0.0
9               0.0              0.0
10              0.0              0.0

## problem

In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\yhk25\.conda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_dropna = df.dropna()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [3]:
df_dropna.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        0 non-null      str
 1   job_title              0 non-null      str
 2   job_location           0 non-null      str
 3   job_via                0 non-null      str
 4   job_schedule_type      0 non-null      str
 5   job_work_from_home     0 non-null      bool
 6   search_location        0 non-null      str
 7   job_posted_date        0 non-null      datetime64[us]
 8   job_no_degree_mention  0 non-null      bool
 9   job_health_insurance   0 non-null      bool
 10  job_country            0 non-null      str
 11  salary_rate            0 non-null      str
 12  salary_year_avg        0 non-null      float64
 13  salary_hour_avg        0 non-null      float64
 14  company_name           0 non-null      str
 15  job_skills             0 non-null      str
 16  job_type_skills        0 non-null      str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 132.0 bytes

In [5]:
df_unique = df.drop_duplicates()
df_unique.info()

<class 'pandas.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  str
 1   job_title              785639 non-null  str
 2   job_location           784595 non-null  str
 3   job_via                785632 non-null  str
 4   job_schedule_type      772975 non-null  str
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  str
 7   job_posted_date        785640 non-null  datetime64[us]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785591 non-null  str
 11  salary_rate            33066 non-null   str
 12  salary_year_avg        22002 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785622 non-null  str
 15  job_skills             668654 non-null  str
 16  job_type_skills        668654 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 271.6 MB

In [6]:
df_filled = df.copy()

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(0)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(0)

df_filled[['salary_year_avg', 'salary_hour_avg']].head(10)

   salary_year_avg  salary_hour_avg
0              0.0              0.0
1              0.0              0.0
2              0.0              0.0
3              0.0              0.0
4              0.0              0.0
5              0.0              0.0
6              0.0              0.0
7              0.0              0.0
8              0.0              0.0
9              0.0              0.0