In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\yhk25\.conda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [4]:
df.index.name = 'job_index'

In [5]:
df.head()

                job_title_short  ...                                    job_type_skills
job_index                        ...
0          Senior Data Engineer  ...                                                NaN
1                  Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2                 Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3                 Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4                 Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]

In [6]:
df.index.dtype

dtype('int64')

In [7]:
df_usa = df[df['job_country'] == 'United States']

In [8]:
df_usa.head()

                job_title_short  ...                                    job_type_skills
job_index                        ...
0          Senior Data Engineer  ...                                                NaN
3                 Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
5                 Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...
6          Senior Data Engineer  ...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
9                Data Scientist  ...  {'analyst_tools': ['excel'], 'cloud': ['azure'...

[5 rows x 17 columns]

In [9]:
df_usa.reset_index(inplace = True)

df_usa

        job_index  ...                                    job_type_skills
0               0  ...                                                NaN
1               3  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
2               5  ...  {'cloud': ['gcp'], 'programming': ['python', '...
3               6  ...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
4               9  ...  {'analyst_tools': ['excel'], 'cloud': ['azure'...
...           ...  ...                                                ...
206287     785673  ...                                                NaN
206288     785685  ...  {'analyst_tools': ['excel'], 'programming': ['...
206289     785692  ...         {'programming': ['python', 'matlab', 'r']}
206290     785703  ...                                                NaN
206291     785705  ...  {'analyst_tools': ['tableau'], 'programming': ...

[206292 rows x 18 columns]

In [10]:
df_usa.set_index('job_index', inplace = True)

In [11]:
df_usa

                job_title_short  ...                                    job_type_skills
job_index                        ...
0          Senior Data Engineer  ...                                                NaN
3                 Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
5                 Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...
6          Senior Data Engineer  ...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
9                Data Scientist  ...  {'analyst_tools': ['excel'], 'cloud': ['azure'...
...                         ...  ...                                                ...
785673           Data Scientist  ...                                                NaN
785685             Data Analyst  ...  {'analyst_tools': ['excel'], 'programming': ['...
785692           Data Scientist  ...         {'programming': ['python', 'matlab', 'r']}
785703             Data Analyst  ...                                                NaN
785705             Data Analyst  ...  {'analyst_tools': ['tableau'], 'programming': ...

[206292 rows x 17 columns]

In [14]:
median_pivot = df_usa.pivot_table(values = 'salary_year_avg', index = 'job_title_short', aggfunc = ['median', 'min', 'max'])
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0

In [17]:
median_pivot.sort_values(by = ('median', 'salary_year_avg'), ascending = False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155000.0         55000.0        475000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Data Scientist                   130000.0         30000.0        960000.0
Software Engineer                130000.0         48982.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Cloud Engineer                   116100.0         42000.0        221844.0
Senior Data Analyst              110000.0         35360.0        425000.0
Business Analyst                  90000.0         35000.0        387460.0
Data Analyst                      90000.0         25000.0        375000.0

In [19]:
median_pivot.sort_index(inplace = True)
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0

In [2]:
median_pivot =  df.pivot_table(
    values='salary_year_avg',
    index='job_title_short',
    aggfunc='median'
)

median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

In [3]:
median_pivot.index.name

'job_title_short'

In [4]:
median_pivot.index.dtype

In [5]:
df_usa = df[df['job_country'] == 'United States']

df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [6]:
df_usa.index

Index([     0,      3,      5,      6,      9,     11,     13,     17,     26,
           27,
       ...
       785625, 785626, 785641, 785648, 785651, 785673, 785685, 785692, 785703,
       785705],
      dtype='int64', length=206292)

In [7]:
df_usa.reset_index(inplace=True)
df_usa

,index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206287,785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
206288,785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
206289,785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
206290,785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
206291,785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [10]:
median_pivot.reset_index(inplace = True)
median_pivot

   level_0  index            job_title_short  salary_year_avg
0        0      0           Business Analyst          85000.0
1        1      1             Cloud Engineer          90000.0
2        2      2               Data Analyst          90000.0
3        3      3              Data Engineer         125000.0
4        4      4             Data Scientist         127500.0
5        5      5  Machine Learning Engineer         106415.0
6        6      6        Senior Data Analyst         111175.0
7        7      7       Senior Data Engineer         147500.0
8        8      8      Senior Data Scientist         155500.0
9        9      9          Software Engineer          99150.0

In [11]:
df_usa.set_index('index', inplace=True)
df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [12]:
median_pivot.set_index('job_title_short', inplace=True)

In [13]:
median_pivot

                           level_0  index  salary_year_avg
job_title_short
Business Analyst                 0      0          85000.0
Cloud Engineer                   1      1          90000.0
Data Analyst                     2      2          90000.0
Data Engineer                    3      3         125000.0
Data Scientist                   4      4         127500.0
Machine Learning Engineer        5      5         106415.0
Senior Data Analyst              6      6         111175.0
Senior Data Engineer             7      7         147500.0
Senior Data Scientist            8      8         155500.0
Software Engineer                9      9          99150.0

In [14]:
median_pivot.sort_index(inplace=True)

In [15]:
median_pivot

                           level_0  index  salary_year_avg
job_title_short
Business Analyst                 0      0          85000.0
Cloud Engineer                   1      1          90000.0
Data Analyst                     2      2          90000.0
Data Engineer                    3      3         125000.0
Data Scientist                   4      4         127500.0
Machine Learning Engineer        5      5         106415.0
Senior Data Analyst              6      6         111175.0
Senior Data Engineer             7      7         147500.0
Senior Data Scientist            8      8         155500.0
Software Engineer                9      9          99150.0

## Problem

In [2]:
df.set_index('job_title_short', inplace = True)
df.head()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [9]:
df.reset_index(drop = True, inplace=True)
df.head()

,index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [10]:
df.set_index('job_title_short', inplace=True)
df.sort_index(inplace=True)
df.head()

,index,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,,
Business Analyst,8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,NaN,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
Business Analyst,60,Business Intelligence Intern,"Dallas, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 13:02:07,False,False,United States,NaN,NaN,NaN,Copart,"['r', 'python', 'sql', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
Business Analyst,66,BI Engineer,Namibia,via Intellijobs.ai,Full-time,False,Namibia,2023-03-05 14:10:49,False,False,Namibia,NaN,NaN,NaN,Innover,"['sql', 'gcp', 'looker', 'tableau']","{'analyst_tools': ['looker', 'tableau'], 'clou..."
Business Analyst,71,Business Analyst,"Tel Aviv-Yafo, Israel",via Comeet,Full-time,False,Israel,2023-09-05 13:50:12,False,False,Israel,NaN,NaN,NaN,ironSource,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
Business Analyst,138,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,NaN,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ..."

In [11]:
median_pivot = df.pivot_table(
    values='salary_year_avg',
    index='job_title_short',
    aggfunc='median'
)

In [12]:
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

In [13]:
median_pivot.reset_index(inplace=True)

In [14]:
median_pivot

             job_title_short  salary_year_avg
0           Business Analyst          85000.0
1             Cloud Engineer          90000.0
2               Data Analyst          90000.0
3              Data Engineer         125000.0
4             Data Scientist         127500.0
5  Machine Learning Engineer         106415.0
6        Senior Data Analyst         111175.0
7       Senior Data Engineer         147500.0
8      Senior Data Scientist         155500.0
9          Software Engineer          99150.0

In [16]:
median_pivot.set_index('job_title_short', inplace=True)

In [17]:
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0